### ISSUE TITLE
small graphical issue

### ISSUE THREAD

**Issue by J3inx** [SenpaiHunters/SpotOn#10]
**Describe the bug**
when pressing the devices button to switch which device audio is being streamed to it has a very confusing form to it

**To Reproduce**
open the devices menu

**Expected behavior**
just to look good

**Screenshots**

<img width="298" alt="Screen Shot 2023-03-31 at 2 33 14 PM" src="https://user-images.githubusercontent.com/125412609/229201757-fd235d61-036a-4cf0-9e3b-5172403bd9c9.png">
looked a bit different earlier but this is the best I could get at the moment
**Desktop (please complete the following information):**
 - OS: mac osx big sur
 - Browser chrome
 - Version newest?

**Additional context**
some of the menus on there seemed to overlap

**Comment by SenpaiHunters** [comment]
Hello! Thank you for reporting the issues, this *should* be fixed next release. It's pretty ugly, I'll have to redo it, Spoify change ways of the border's and that messed up the look! If you have any questions or concerns feel free to comment them!
