### ISSUE TITLE
Options won't close

### ISSUE THREAD

**Issue by dieptp** [SenpaiHunters/SpotOn#4]
As I said, When I enable "options" there is no way to turn it off, except to refresh

**Comment by SenpaiHunters** [comment]
Hello, and thank you for reporting this problem. Currently (V 0.4), there is a 'close' button, but it is very difficult to see (screenshot attached for reference); in version 0.5 (coming), I intend to make this more visible! For the time being, the only way to remove the 'options' is to either press 'close' or reload. I hope this was helpful.


<img width="162" alt="image" src="https://user-images.githubusercontent.com/103985728/198559086-569ab494-ee8d-4e18-b73c-0fb0481ef121.png">
